### PR TITLE
feat: add a nix flake

### PR DESCRIPTION
**Pull request by Ultra980**
I wrote a nix derivation and added it to a flake, so NixOS users can easily install the theme.

### CODE REVIEW

**Comment by mngshm** [comment]
Hey @Ultra980 can you please show a demo of the nix flake installation and if the theme works on it or not ? I don't have nixos installed, so there's no way I can test it. 

Will merge it once tested.

**Comment by gr4phite** [comment]
To install the theme flake (easily), you need a flake nixOS config. [I've got one](https://github.com/ultra980/nixos-dotfiles) , and to install it I added it as an input in `flake.nix` and installed it in `configuration.nix` (under `hosts/hermes`). I couldn't find any legacy gtk apps though, so I can't test it.

**Comment by gr4phite** [comment]
I also made a gradience theme for everblush, I could make a flake for that as well.

**Comment by mngshm** [comment]
Hey, can you show a screenshot of the gradience theme ? We'll make a separate repo for that and you can add the theme on the that repo. :) 

Sorry for the late reply.

**Comment by gr4phite** [comment]
I already added it to their official community repo, in this file: https://github.com/GradienceTeam/Community/blob/next/curated/everblush.json

I'll post some screenshots when I have time.

**Pull request merged**
