### PR TITLE
add gtk-2 support

### PR DESCRIPTION
**Pull request by siduck**
- This would make showing it in lxappearance
- Since qt5ct can use gtk-2 for qt apps then  we can use this theme for qt themes too

image

simplescreen recorder   (QT) on left and lxappearance on right

### CODE REVIEW

**Comment by siduck** [comment]
why?

**Comment by siduck** [comment]
image

 qt apps without gtk-2

**Comment by mngshm** [comment]
> why?

I shouldnt merge?

**Comment by siduck** [comment]
ig its time to make own colorscheme now :)

**Comment by mngshm** [comment]
Wait wth are you talking?

**Comment by siduck** [comment]
oh lol nvm, i thought you just closed the PR. I didnt read properly xD . just wokeup

**Comment by mngshm** [comment]
😂😂

**Comment by mngshm** [comment]
Why would I lol I checked even when am walking on highway

**Comment by siduck** [comment]
> Why would I lol I checked even when am walking on highway

oh i forgot to add it in makefile . add 	@cp -rv assets gtk-2.0 "$(INSTALL_DIR)"


this line 
image

**Comment by mngshm** [comment]
Ok I'll do :))

**Pull request merged**
